language: node_js
env:
  matrix:
    - CI=true TRAVIS=true

#  global:
#    - secure: RN0H1IlQVGU7GSdYVmpUJZdWQFyyDGZdZhfoLtjZOQLbGwPkw2ZNanij1DfXuSHPX/T+8/tURYiP3PgbyLif7Uiktyp/XecqYGaUCYpr491ovwV37DapzwAJeyKR9FTDgdRN0DT2x8BijLz8iIj+D+CcwnOs1udiqAuQ9FY8gyGefV/ubRt3hRS4vJyfaL/+yApKoFCxU8O9ktlR1Y29gsd8Y0zpateFPDXmIN6sHdDqiFrefqso2nUQL6R7Ow1cV++M+cNN4InDZfNte9qaZfEyJ0b/Fp3aHq/oKA2HdFdy6zNzjZBJ2kKp0VWXzILbtC/B1WU93QfGcEaQjY9KNwzcij/8nPZ0+h0xC6c146lnID5Wu7HFuZdds8cBThb/10FEBEMuK5uL7yJltHLFvyseB0PE2H139BS4ek4RtzP81P/CCVRQtzFlSz2U7YecRCyorLJ4UwX3pdbhEw0cTuppQ4KT8JL/kQ+IZiVZpHJ9TiMwe5lhxDsEU6WPT0WP/nLR0nin3P0GD9a4RCJb6ZLezHbHUZIOor+JkiV/xFfIOkOi46xJ3jowNk6F3GDc2NOkI0dopdGetr7gfwv0RebC2BI6Kna70FQzRQmGACo8Ritehk/E5DYQZsq26LGvPq7Mjbg0g6T6ln6uVmF5FlTu5wwzmtL2eCGNlLBawAs=
#    - secure: IAN10TRpFdb8WrYz6jHmBO/UZmjREK5Wrx1bDV8JwV4vonJWNtu6GqtPtCx+4iQV8zkjpNk8RHu7+KpBV54o+1AoWGG16Tvk1nZ9E07iH3p+Cnd/RHM2Y0jKTggOJCEnoQwMDEuBZByVlMgjvOzwzLYi5l1eY1Blusa2Sw6TeGxct6QaelFFppk+6CYhHt7GE5urUrbfcsdJryc2PczeoPDOPVkZYaiLuYkvmS2XgHV2cbVfJ3sVrodbBW5WyHyO/yy2Bvf5gLlXORHkjlhCesOm3krc0nmmFqfYwqjQ/w3CIAihk+Kup6OU/EYUzY1sIVqcoVGWk1lXlblglBxE5PmVv3E9qx/IYXeorcqpx//w7WyPHl968BnFS1oLxGBj+0RG2avFJAjSdqlhix6fz/wOt0NzJjRgRfCHlSc7WLkxBbYUs7BqiNYqjfpWsq33qP+aW3avYP3qwYYY6Zy5aVtEPaqRKbJy4Xx7T0hHcSHRAGen73Ec5wHmN5gPfW5geoQOB5uYbSPO8ye663/Vb8XAZRxHBzxoW2TY+38HM/ICL60p3GaVBvUvp6lEwFUE7i0iMvE8cwih+0THofKSkGgVSRGz/uF0fdBDY7mxjGF8tN5CxFxLZxSQMA0PR1xkV6HRs7o6fdWWWBa9CpXuil51Y+Ah5CMvUrVEd9JxaNs=

sudo: false


## blacklist
#branches:
#  except:
#    - legacy
#    - experimental
#
## whitelist
#branches:
#  only:
#    - master
#    - stable

node_js:
  - "iojs"
#  - "iojs-v1.0"
#  - "0.10"

script:
  - npm run test

after_script:
  - npm run coveralls
  - npm run test-sl

addons:
  sauce_connect: true


notifications:
  email:
    recipients:
      - qiuzhongleiabc@126.com
    on_success: never
    on_failure: always

